[theme]
primaryColor = "#1E90FF"       # Customize as needed
backgroundColor = "#FFFFFF"    # White background
secondaryBackgroundColor = "#F0F2F6"  # Optional, for panels
textColor = "#000000"          # Black text for contrast
font = "sans serif"            # Font style
